"""Intent names supported by the Runtime interaction layer."""

CONTINUE = "CONTINUE"
CREATE = "CREATE"
EXECUTE = "EXECUTE"
PAUSE = "PAUSE"
RESUME = "RESUME"
CANCEL = "CANCEL"
STATUS = "STATUS"
EXPLAIN = "EXPLAIN"
APPROVE = "APPROVE"
REJECT = "REJECT"
SWITCH_WORKSPACE = "SWITCH_WORKSPACE"
UNKNOWN = "UNKNOWN"

ALL_INTENTS = (
    CONTINUE,
    CREATE,
    EXECUTE,
    PAUSE,
    RESUME,
    CANCEL,
    STATUS,
    EXPLAIN,
    APPROVE,
    REJECT,
    SWITCH_WORKSPACE,
)
