#!/usr/bin/env python3
"""Comment quality audit — detects AI-tool attribution and low-value comments.

This check is part of the public-source release gate.
Run: python scripts/comment_quality_audit.py [path]

Allowed contexts (not flagged):
  - "Claude Provider", "OpenAI-compatible API", "Codex model integration"
  - Legitimate product behavior descriptions using "AI" as product identity

Flagged patterns (require review):
  - "Generated by [AI tool]", "added by [AI tool]", "written by [AI tool]"
  - "Co-authored-by: [AI tool]"
  - Tentative language: "This should probably work", "Let's try"
  - Conversational: "The user asked", "As requested by the user"
  - Tool-name references in non-provider contexts
"""

import argparse
import re
import sys
from pathlib import Path

# Patterns that signal AI-tool attribution or low-value commentary
AI_ATTRIBUTION_PATTERNS = [
    (re.compile(r"(?:generated|added|written|created|completed|implemented)\s+by\s+(?:Claude|Codex|ChatGPT|GPT|AI\s+assistant)", re.IGNORECASE),
     "AI-tool attribution claim"),
    (re.compile(r"co-authored-by:\s*(?:Claude|Codex|ChatGPT|AI|OpenAI)", re.IGNORECASE),
     "AI co-author trailer"),
    (re.compile(r"this\s+should\s+probably\s+work", re.IGNORECASE),
     "Tentative/low-confidence comment"),
    (re.compile(r"let'?s\s+try", re.IGNORECASE),
     "Tentative/exploratory comment"),
    (re.compile(r"(?:the\s+user\s+asked|as\s+requested\s+by\s+the\s+user|the\s+user\s+wants)", re.IGNORECASE),
     "Conversational AI self-reference"),
    (re.compile(r"@(?:claude|codex|chatgpt|gpt|ai-assistant)\b", re.IGNORECASE),
     "AI tool @-mention"),
    (re.compile(r"#\s*(?:TODO|FIXME|HACK|XXX):\s*(?:Claude|Codex|ChatGPT)", re.IGNORECASE),
     "AI-tool-labeled task marker"),
]

# Allowed contexts — these are NOT flagged
ALLOWED_CONTEXTS = [
    re.compile(r"Claude\s+Provider", re.IGNORECASE),
    re.compile(r"OpenAI-compatible\s+API", re.IGNORECASE),
    re.compile(r"Codex\s+model\s+integration", re.IGNORECASE),
    re.compile(r"Anthropic\s+(?:Provider|API|SDK)", re.IGNORECASE),
    re.compile(r"delegate_to_claude", re.IGNORECASE),  # legitimate feature name
]

EXCLUDE_DIRS = {
    ".git", ".venv", "node_modules", "target", "build", ".gradle",
    ".apeir", ".nous", ".audit", "artifacts", "reports", "tests",
    "__pycache__", ".pytest_cache", "dist", ".local-archive",
}

CHECK_EXTENSIONS = {".py", ".ts", ".tsx", ".rs", ".js", ".jsx"}
SKIP_FILES = {"comment_quality_audit.py", "repository_identity_audit.py"}


def is_allowed_context(line: str) -> bool:
    """Check if the line is in an allowed context (e.g., provider name)."""
    return any(p.search(line) for p in ALLOWED_CONTEXTS)


def audit_file(filepath: Path) -> list[dict]:
    """Audit a single file for AI attribution patterns."""
    findings = []
    try:
        content = filepath.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return findings

    lines = content.split("\n")
    for i, line in enumerate(lines, start=1):
        if is_allowed_context(line):
            continue
        for pattern, label in AI_ATTRIBUTION_PATTERNS:
            if pattern.search(line):
                findings.append({
                    "file": str(filepath),
                    "line": i,
                    "pattern": label,
                    "text": line.strip()[:120],
                })
                break  # One finding per line
    return findings


def collect_files(root: Path) -> list[Path]:
    """Collect all checkable files, excluding vendor/test directories."""
    files = []
    for ext in CHECK_EXTENSIONS:
        for f in root.rglob(f"*{ext}"):
            parts = f.parts
            if any(excl in parts for excl in EXCLUDE_DIRS):
                continue
            if f.name in SKIP_FILES:
                continue
            files.append(f)
    return files


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(errors="replace")
    parser = argparse.ArgumentParser(description="Audit code comments for AI-tool attribution")
    parser.add_argument("path", nargs="?", default=".", help="Root path to audit")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    root = Path(args.path).resolve()
    files = collect_files(root)

    all_findings = []
    for f in files:
        all_findings.extend(audit_file(f))

    if args.json:
        import json
        print(json.dumps(all_findings, indent=2, ensure_ascii=False))
    else:
        if not all_findings:
            print("PASS: No AI-tool attribution patterns found in code comments.")
            return 0

        print(f"Found {len(all_findings)} potential AI-attribution issues:\n")
        for finding in all_findings:
            print(f"  {finding['file']}:{finding['line']} [{finding['pattern']}]")
            print(f"    {finding['text']}\n")

        return 1


if __name__ == "__main__":
    sys.exit(main())
