"""
Repository Identity Audit — Contextual scan for AI attribution patterns.

This script scans the repository for AI-tool attribution traces that should
not appear in a public, maintainer-owned open-source project. It distinguishes
between:

  BLOCKED: Attribution language (e.g., "generated by Claude", "Codex wrote this")
  ALLOWED:  Legitimate product/API references (e.g., "Claude provider", "ANTHROPIC_API_KEY")

Run as: python scripts/repository_identity_audit.py [--fix]
"""

import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# ── Patterns ────────────────────────────────────────────────────────────────

# Patterns that indicate AI self-attribution (BLOCK)
ATTRIBUTION_PATTERNS = [
    # Direct attribution
    (re.compile(r"(?i)generated\s+by\s+(Claude|Codex|ChatGPT|GPT|OpenAI|AI)"), "AI generation attribution"),
    (re.compile(r"(?i)(written|implemented|created|built)\s+by\s+(Claude|Codex)"), "AI authorship claim"),
    (re.compile(r"(?i)(uploaded|pushed|committed)\s+by\s+(Codex|Claude)"), "AI commit attribution"),
    (re.compile(r"(?i)(Claude|Codex)\s+(completed|finished|generated|produced|delivered)"), "AI completion claim"),
    (re.compile(r"(?i)AI-generated\s+(code|implementation|solution|fix|feature)"), "AI-generated label"),
    (re.compile(r"(?i)auto-generated\s+by\s+(AI|Claude|Codex|agent)"), "Auto-generation attribution"),
    (re.compile(r"(?i)co-authored-by\s*:\s*(Claude|Codex|ChatGPT|AI)"), "AI co-author trailer"),
    # Model self-reference
    (re.compile(r"(?i)as\s+an\s+(AI|language\s+model|LLM)\s*(,|\s+I)"), "AI self-reference"),
    (re.compile(r"(?i)TODO\s+from\s+(Claude|Codex)"), "AI-sourced TODO"),
    (re.compile(r"(?i)(Claude|Codex|ChatGPT)\s+suggested"), "AI suggestion attribution"),
    # Process references
    (re.compile(r"(?i)(Claude\s+Code|Codex)\s+(task|upload|deployment|review|audit|pass)"), "AI process reference"),
    (re.compile(r"(?i)The\s+user\s+asked\s+(me|us|Claude|Codex)\s+to"), "Conversational trace"),
]

# Patterns that ARE legitimate product/API references (ALLOW)
ALLOWED_PRODUCT_PATTERNS = [
    re.compile(r"(?i)ANTHROPIC_API_KEY"),
    re.compile(r"(?i)OPENAI_API_KEY"),
    re.compile(r"(?i)Anthropic\s+(Claude|API|SDK|Provider|Adapter|compatible)"),
    re.compile(r"(?i)OpenAI(-compatible)?\s+(API|Provider|Adapter|SDK|model)"),
    re.compile(r"(?i)Claude\s+(provider|model|API|adapter|endpoint|family)"),
    re.compile(r"(?i)GPT\s+(model|family|provider|API|adapter)"),
    re.compile(r"(?i)Codex\s+(model|adapter|provider)"),  # codex as a model name, not tool name
    re.compile(r"(?i)DeepSeek\s+(provider|model|API|chat)"),
    re.compile(r"(?i)model_family\s*==\s*[\"']claude[\"']"),
    re.compile(r"(?i)(OpenAI|Anthropic|DeepSeek|Ollama|Google|Meta)(\s+|\s+and\s+)(compatible|provider|adapter|model|API)"),
    re.compile(r"(?i)^\s*[\"'](claude|gpt|openai|anthropic|deepseek|ollama)[\"']\s*:"),
]

# Directories to skip entirely
SKIP_DIRS = {
    ".git", ".venv", "venv", "__pycache__", ".tox",
    "node_modules", "target", "build", "dist",
    ".mypy_cache", ".pytest_cache", ".ruff_cache", "tests",
    "RemoteTerminal",  # Separate Android project
}

# Files to skip
SKIP_FILES = {
    "REPOSITORY_IDENTITY_AUDIT.md",   # This audit's own report
    "BRANCH_CLEANUP_PLAN.md",         # This audit's own plan
    "Cargo.lock",                      # Auto-generated
    "package-lock.json",               # Auto-generated
    "pnpm-lock.yaml",                  # Auto-generated
    "repository_identity_audit.py",    # Audit pattern definitions
}

# File extensions to scan
CODE_EXTENSIONS = {".py", ".ts", ".tsx", ".rs", ".js", ".jsx", ".kt", ".java", ".toml"}
DOC_EXTENSIONS = {".md", ".mdx", ".rst", ".txt"}
SCAN_EXTENSIONS = CODE_EXTENSIONS | DOC_EXTENSIONS


def classify_line(line: str, file_path: Path) -> list[tuple[str, str]]:
    """Return list of (pattern_description, matched_text) for blocked patterns.

    Filters out matches that overlap with allowed product references."""
    findings = []

    # Check allowed patterns first
    allowed_spans = set()
    for pat in ALLOWED_PRODUCT_PATTERNS:
        for m in pat.finditer(line):
            allowed_spans.add(range(m.start(), m.end()))

    # Check blocked patterns
    for pat, desc in ATTRIBUTION_PATTERNS:
        for m in pat.finditer(line):
            match_range = range(m.start(), m.end())
            # Check if this match overlaps with an allowed reference
            is_allowed = any(
                match_range.start >= ar.start and match_range.stop <= ar.stop
                for ar in allowed_spans
            )
            if not is_allowed:
                findings.append((desc, m.group().strip()))

    return findings


def scan_file(file_path: Path, root: Path = REPO_ROOT) -> list[dict]:
    """Scan a single file for attribution patterns."""
    findings = []
    try:
        content = file_path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return findings

    for lineno, line in enumerate(content.splitlines(), 1):
        matches = classify_line(line, file_path)
        for desc, matched in matches:
            findings.append({
                "file": str(file_path.relative_to(root)),
                "line": lineno,
                "pattern": desc,
                "text": matched[:120],
            })

    # Check filename itself
    filename = file_path.name.lower()
    if re.search(r"(?i)(claude|codex|chatgpt|ai.generated)", filename):
        # Filename containing tool name — flag unless it's a provider adapter
        if "provider" not in filename and "adapter" not in filename:
            findings.append({
                "file": str(file_path.relative_to(root)),
                "line": 0,
                "pattern": "AI tool reference in filename",
                "text": file_path.name,
            })

    return findings


def scan_repository(root: Path) -> dict:
    """Scan entire repository for AI attribution patterns."""
    all_findings = []
    files_scanned = 0

    for dirpath, dirnames, filenames in os.walk(root):
        # Filter out skip directories
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")]

        current_dir = Path(dirpath)
        # Skip paths deep in build/venv artifacts
        if any(skip in current_dir.parts for skip in {".venv", "node_modules", "__pycache__"}):
            continue

        for fname in filenames:
            if fname in SKIP_FILES:
                continue

            ext = Path(fname).suffix.lower()
            if ext not in SCAN_EXTENSIONS:
                continue

            file_path = current_dir / fname
            findings = scan_file(file_path, root)
            all_findings.extend(findings)
            files_scanned += 1

    return {
        "files_scanned": files_scanned,
        "findings": all_findings,
    }


def format_report(result: dict) -> str:
    """Format findings into a readable report."""
    lines = []
    lines.append("=" * 72)
    lines.append("Repository Identity Audit Report")
    lines.append(f"Files scanned: {result['files_scanned']}")
    lines.append(f"Issues found:  {len(result['findings'])}")
    lines.append("=" * 72)

    if not result["findings"]:
        lines.append("\nPASS: No AI attribution patterns found.")
        return "\n".join(lines)

    # Group by file
    by_file: dict[str, list] = {}
    for f in result["findings"]:
        by_file.setdefault(f["file"], []).append(f)

    lines.append(f"\n{f'ISSUES BY FILE ({len(by_file)} files affected)':-^72}\n")
    for filepath, issues in sorted(by_file.items()):
        lines.append(f"  {filepath}")
        for issue in issues:
            loc = f"L{issue['line']}" if issue["line"] > 0 else "name"
            lines.append(f"     {loc}: [{issue['pattern']}]")
            lines.append(f"          {issue['text']}")
        lines.append("")

    lines.append(f"{'SUMMARY':-^72}")
    by_pattern: dict[str, int] = {}
    for f in result["findings"]:
        by_pattern[f["pattern"]] = by_pattern.get(f["pattern"], 0) + 1

    for pattern, count in sorted(by_pattern.items(), key=lambda x: -x[1]):
        lines.append(f"  {count:3d}  {pattern}")

    return "\n".join(lines)


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Repository Identity Audit")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("path", nargs="?", default=str(REPO_ROOT), help="Path to scan")
    args = parser.parse_args()

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(errors="replace")

    result = scan_repository(Path(args.path).resolve())

    if args.json:
        import json
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print(format_report(result))

    # Exit with non-zero if issues found (for CI)
    if result["findings"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
